---
name: Check and Preview

on:
  workflow_dispatch:
  # execute on pull request event
  pull_request:
  push:
    branches:
      - $default-branch
      - development
      - master

# permissions needed to write a comment to the PR
permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  eslint:
    name: 🧑‍💻 Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: 📝 Lint Code Base
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_PYTHON_RUFF_FORMAT: false
          VALIDATE_SPELL_CODESPELL: false
  codespell:
    name: 🔤 Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: 🔤 Check spelling
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          skip: "*.pdf,*/*.md,index.md,README.md"
          check_filenames: true
